spring:
  datasource:
    url: jdbc:mysql://192.168.1.198:3308/popuman?characterEncoding=utf-8
    username: root
    password: poputar123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: com.utils.MySQL5InnoDBDialectUtf8
  jackson:
    serialization:
      indent-output: true
  messages:
    encoding: UTF-8
    basename: i18n/messages
  redis:
    database: 1
    host: 192.168.1.198
    port: 6379
    password: 
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
    timeout: 5000
    
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000